#!/bin/sh
set -e

# Dynamically generate runtime configuration for the SPA
cat <<EOF > /usr/share/nginx/html/config.js
window.__HUMID1_CONFIG__ = {
  THINGSBOARD_URL: "${THINGSBOARD_URL:-${THINGSBOARD_SERVER_URL:-${VITE_THINGSBOARD_URL:-${VITE_THINGSBOARD_SERVER_URL:-https://app.humid1.com}}}}",
  AUTHENTIK_URL: "${AUTHENTIK_URL:-${VITE_AUTHENTIK_URL:-https://auth.humid1.com}}",
  AUTHENTIK_APP_SLUG: "${AUTHENTIK_APP_SLUG:-${AUTHENTIK_SLUG:-${VITE_AUTHENTIK_APP_SLUG:-${VITE_AUTHENTIK_SLUG:-humid1-dash}}}}",
  AUTHENTIK_CLIENT_ID: "${AUTHENTIK_CLIENT_ID:-${VITE_AUTHENTIK_CLIENT_ID:-7nvidWHfM8C3wE3VKGqFNGFNnl9aou46mL5kporI}}",
  DASHBOARD_URL: "${DASHBOARD_URL:-${VITE_DASHBOARD_URL:-https://dash.humid1.com}}",
  DEFAULT_DEVICE_NAME: "${DEFAULT_DEVICE_NAME:-${VITE_DEFAULT_DEVICE_NAME:-HUMID1-CABINET-01}}",
  DASHBOARD_VERSION: "${DASHBOARD_VERSION:-${VITE_DASHBOARD_VERSION:-1.2.0-beta}}",
  DASHBOARD_REVISION: "${DASHBOARD_REVISION:-${VITE_DASHBOARD_REVISION:-rev-dev-continuous}}"
};
console.info("[HUMID1] Runtime domain config loaded successfully.", window.__HUMID1_CONFIG__);
EOF

cat <<EOF > /usr/share/nginx/html/env-config.js
window.__ENV__ = {
  VITE_APP_TITLE: "${VITE_APP_TITLE:-HUMID1 Telemetry Dashboard}",
  VITE_APP_DESCRIPTION: "${VITE_APP_DESCRIPTION:-Precision Humidor Monitoring & Telemetry Stack}",
  VITE_DASHBOARD_URL: "${DASHBOARD_URL:-${VITE_DASHBOARD_URL:-https://dash.humid1.com}}",
  VITE_THINGSBOARD_URL: "${THINGSBOARD_URL:-${THINGSBOARD_SERVER_URL:-${VITE_THINGSBOARD_URL:-${VITE_THINGSBOARD_SERVER_URL:-https://app.humid1.com}}}}",
  VITE_AUTHENTIK_URL: "${AUTHENTIK_URL:-${VITE_AUTHENTIK_URL:-https://auth.humid1.com}}",
  VITE_AUTHENTIK_APP_SLUG: "${AUTHENTIK_APP_SLUG:-${AUTHENTIK_SLUG:-${VITE_AUTHENTIK_APP_SLUG:-${VITE_AUTHENTIK_SLUG:-humid1-dash}}}}",
  VITE_AUTHENTIK_CLIENT_ID: "${AUTHENTIK_CLIENT_ID:-${VITE_AUTHENTIK_CLIENT_ID:-7nvidWHfM8C3wE3VKGqFNGFNnl9aou46mL5kporI}}",
  VITE_DEFAULT_DEVICE_NAME: "${DEFAULT_DEVICE_NAME:-${VITE_DEFAULT_DEVICE_NAME:-HUMID1-CABINET-01}}",
  VITE_APP_REDIRECT_URI: "${VITE_APP_REDIRECT_URI:-}",
  VITE_DASHBOARD_VERSION: "${DASHBOARD_VERSION:-${VITE_DASHBOARD_VERSION:-1.2.0-beta}}",
  VITE_DASHBOARD_REVISION: "${DASHBOARD_REVISION:-${VITE_DASHBOARD_REVISION:-rev-dev-continuous}}"
};
EOF

# Execute standard CMD (starts Nginx)
exec "$@"

