version: '3.8'

services:
  humid1-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/humiditron/tb-dash-2:latest
    container_name: humid1-dashboard
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - THINGSBOARD_URL=https://app.humid1.com
      - AUTHENTIK_URL=https://auth.humid1.com
      - AUTHENTIK_APP_SLUG=humid1-dash
      - AUTHENTIK_CLIENT_ID=7nvidWHfM8C3wE3VKGqFNGFNnl9aou46mL5kporI
      - DASHBOARD_URL=https://dash.humid1.com
      - DEFAULT_DEVICE_NAME=HUMID1-CABINET-01
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
