version: '3.8'

services:
  humid1-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/humiditron/tb-dash-2:latest
    container_name: humid1-dashboard
    restart: unless-stopped
    #ports:
    #  - "5000"
    environment:
      - NODE_ENV=production
      - DASHBOARD_URL=https://dash.humid1.com
      - THINGSBOARD_SERVER_URL=https://app.humid1.com
      - AUTHENTIK_URL=https://auth.humid1.com
      - AUTHENTIK_SLUG=humid1-dash
      - AUTHENTIK_CLIENT_ID=7nvidWHfM8C3wE3VKGqFNGFNnl9aou46mL5kporI
      - CAPTCHA_URL=https://cap.humid1.com
      - CHAT_URL=https://chat.humid1.com
      - SSO_AUTH_ENDPOINT=https://app.humid1.com/oauth2/authorization/1efd3960-a10b-11f1-b530-9b9631e0c365
      - DEFAULT_DEVICE_NAME=HUMID1-CABINET-01
    #healthcheck:
    #  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/healthz"]
    #  interval: 30s
    #  timeout: 5s
    #  retries: 3
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
